language: node_js
node_js:
  - node
cache: npm

script:
  - npm run build

deploy:
  - provider: s3
    bucket: mattmoriarity.com
    skip_cleanup: true
    acl: public_read
    local_dir: dist
  - provider: s3
    bucket: mattmoriarity.com
    skip_cleanup: true
    local_dir: templates
    upload_dir: _templates
